sudo: required
dist: trusty
language: python
python:
  - "3.4"
virtualenv:
    system_site_packages: false
before_install:
    - sudo apt-get update
    - sudo apt-get -y install python3 python3-pip python3-nose python3-coverage
    - sudo pip3 install -U python-coveralls
install:
    - sudo apt-get -y install python3-pyqt4 python3-lxml
    - sudo pip3 install -U requests beautifulsoup4

# command to run tests
script: PYTHONPATH=. nosetests3 -v --logging-level=INFO --with-coverage --cover-erase --cover-inclusive --cover-package=omad

after_success:
    - coveralls
