sudo: false
language: python
python:
  - "3"
virtualenv:
    system_site_packages: true
addons:
  apt:
    packages:
    - python3
    - python3-pip
    - python3-pyqt4
before_install:
    - pip3 install requests beautifulsoup4
    - pip3 install coverage python-coveralls

# command to run tests
script: PYTHONPATH=. nosetests3 -v --logging-level=INFO --with-coverage --cover-erase --cover-inclusive --cover-package=omad

after_success:
    - coveralls
