sudo: false
language: python
python:
  - "2.7"
virtualenv:
    system_site_packages: true
addons:
  apt:
    packages:
    - python 
    - python-pip
    - python-qt4
before_install:
    - pip install requests beautifulsoup
    - pip install coverage python-coveralls
    - pip install requests[security]
    
# command to run tests
script: nosetests --verbose --logging-level=INFO --with-coverage --cover-inclusive --cover-package=omad -a '!travisFail'

after_success:
    - coveralls
